// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names
// coverage:ignore-file

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Auto-generated FFI bindings for AnyChat C API.
/// DO NOT EDIT - regenerate via: dart run ffigen
///
class AnyChatNativeBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  AnyChatNativeBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  AnyChatNativeBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Free a list allocated by the SDK. The structs themselves are also freed.
  void anychat_free_message_list(
    ffi.Pointer<AnyChatMessageList_C> list,
  ) {
    return _anychat_free_message_list(
      list,
    );
  }

  late final _anychat_free_message_listPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<AnyChatMessageList_C>)>>('anychat_free_message_list');
  late final _anychat_free_message_list = _anychat_free_message_listPtr
      .asFunction<void Function(ffi.Pointer<AnyChatMessageList_C>)>();

  void anychat_free_conversation_list(
    ffi.Pointer<AnyChatConversationList_C> list,
  ) {
    return _anychat_free_conversation_list(
      list,
    );
  }

  late final _anychat_free_conversation_listPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<AnyChatConversationList_C>)>>(
      'anychat_free_conversation_list');
  late final _anychat_free_conversation_list =
      _anychat_free_conversation_listPtr
          .asFunction<void Function(ffi.Pointer<AnyChatConversationList_C>)>();

  void anychat_free_friend_list(
    ffi.Pointer<AnyChatFriendList_C> list,
  ) {
    return _anychat_free_friend_list(
      list,
    );
  }

  late final _anychat_free_friend_listPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<AnyChatFriendList_C>)>>(
      'anychat_free_friend_list');
  late final _anychat_free_friend_list = _anychat_free_friend_listPtr
      .asFunction<void Function(ffi.Pointer<AnyChatFriendList_C>)>();

  /// Register a new account.
  /// verify_code: SMS/e-mail verification code.
  /// nickname:    pass empty string or NULL to skip.
  /// client_version: client version string (e.g. "1.0.0"), can be NULL
  int anychat_auth_register(
    AnyChatAuthHandle handle,
    ffi.Pointer<ffi.Char> phone_or_email,
    ffi.Pointer<ffi.Char> password,
    ffi.Pointer<ffi.Char> verify_code,
    int device_type,
    ffi.Pointer<ffi.Char> nickname,
    ffi.Pointer<ffi.Char> client_version,
    ffi.Pointer<AnyChatAuthTokenCallback_C> callback,
  ) {
    return _anychat_auth_register(
      handle,
      phone_or_email,
      password,
      verify_code,
      device_type,
      nickname,
      client_version,
      callback,
    );
  }

  late final _anychat_auth_registerPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  AnyChatAuthHandle,
                  ffi.Pointer<ffi.Char>,
                  ffi.Pointer<ffi.Char>,
                  ffi.Pointer<ffi.Char>,
                  ffi.Int32,
                  ffi.Pointer<ffi.Char>,
                  ffi.Pointer<ffi.Char>,
                  ffi.Pointer<AnyChatAuthTokenCallback_C>)>>(
      'anychat_auth_register');
  late final _anychat_auth_register = _anychat_auth_registerPtr.asFunction<
      int Function(
          AnyChatAuthHandle,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<AnyChatAuthTokenCallback_C>)>();

  /// Create a new client. Returns NULL on failure.
  /// The caller owns the handle and must destroy it with anychat_client_destroy().
  AnyChatClientHandle anychat_client_create(
    ffi.Pointer<AnyChatClientConfig_C> config,
  ) {
    return _anychat_client_create(
      config,
    );
  }

  late final _anychat_client_createPtr = _lookup<
      ffi.NativeFunction<
          AnyChatClientHandle Function(
              ffi.Pointer<AnyChatClientConfig_C>)>>('anychat_client_create');
  late final _anychat_client_create = _anychat_client_createPtr.asFunction<
      AnyChatClientHandle Function(ffi.Pointer<AnyChatClientConfig_C>)>();

  /// Destroy the client and release all resources.
  /// Must not be called while callbacks are in flight on other threads.
  void anychat_client_destroy(
    AnyChatClientHandle handle,
  ) {
    return _anychat_client_destroy(
      handle,
    );
  }

  late final _anychat_client_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(AnyChatClientHandle)>>(
          'anychat_client_destroy');
  late final _anychat_client_destroy = _anychat_client_destroyPtr
      .asFunction<void Function(AnyChatClientHandle)>();

  /// Login with account/password and automatically establish WebSocket connection.
  /// Note: WebSocket auto-reconnect is handled internally by the SDK.
  /// client_version: client version string (e.g. "1.0.0"), can be NULL
  int anychat_client_login(
    AnyChatClientHandle handle,
    ffi.Pointer<ffi.Char> account,
    ffi.Pointer<ffi.Char> password,
    int device_type,
    ffi.Pointer<ffi.Char> client_version,
    ffi.Pointer<AnyChatAuthTokenCallback_C> callback,
  ) {
    return _anychat_client_login(
      handle,
      account,
      password,
      device_type,
      client_version,
      callback,
    );
  }

  late final _anychat_client_loginPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  AnyChatClientHandle,
                  ffi.Pointer<ffi.Char>,
                  ffi.Pointer<ffi.Char>,
                  ffi.Int32,
                  ffi.Pointer<ffi.Char>,
                  ffi.Pointer<AnyChatAuthTokenCallback_C>)>>(
      'anychat_client_login');
  late final _anychat_client_login = _anychat_client_loginPtr.asFunction<
      int Function(
          AnyChatClientHandle,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<AnyChatAuthTokenCallback_C>)>();

  /// Logout: disconnect WebSocket and call HTTP logout endpoint.
  int anychat_client_logout(
    AnyChatClientHandle handle,
    ffi.Pointer<AnyChatAuthResultCallback_C> callback,
  ) {
    return _anychat_client_logout(
      handle,
      callback,
    );
  }

  late final _anychat_client_logoutPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(AnyChatClientHandle,
                  ffi.Pointer<AnyChatAuthResultCallback_C>)>>(
      'anychat_client_logout');
  late final _anychat_client_logout = _anychat_client_logoutPtr.asFunction<
      int Function(
          AnyChatClientHandle, ffi.Pointer<AnyChatAuthResultCallback_C>)>();

  /// Check if the user is currently logged in. Returns 1 if logged in, 0 otherwise.
  int anychat_client_is_logged_in(
    AnyChatClientHandle handle,
  ) {
    return _anychat_client_is_logged_in(
      handle,
    );
  }

  late final _anychat_client_is_logged_inPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(AnyChatClientHandle)>>(
          'anychat_client_is_logged_in');
  late final _anychat_client_is_logged_in = _anychat_client_is_logged_inPtr
      .asFunction<int Function(AnyChatClientHandle)>();

  /// Get current auth token (if logged in). Returns 0 on success, -1 if not logged in.
  int anychat_client_get_current_token(
    AnyChatClientHandle handle,
    ffi.Pointer<AnyChatAuthToken_C> out_token,
  ) {
    return _anychat_client_get_current_token(
      handle,
      out_token,
    );
  }

  late final _anychat_client_get_current_tokenPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  AnyChatClientHandle, ffi.Pointer<AnyChatAuthToken_C>)>>(
      'anychat_client_get_current_token');
  late final _anychat_client_get_current_token =
      _anychat_client_get_current_tokenPtr.asFunction<
          int Function(AnyChatClientHandle, ffi.Pointer<AnyChatAuthToken_C>)>();

  /// Returns the current connection state (ANYCHAT_STATE_*).
  int anychat_client_get_connection_state(
    AnyChatClientHandle handle,
  ) {
    return _anychat_client_get_connection_state(
      handle,
    );
  }

  late final _anychat_client_get_connection_statePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(AnyChatClientHandle)>>(
          'anychat_client_get_connection_state');
  late final _anychat_client_get_connection_state =
      _anychat_client_get_connection_statePtr
          .asFunction<int Function(AnyChatClientHandle)>();

  /// Register a callback for connection state changes.
  /// Pass NULL to clear a previously registered callback.
  /// userdata is passed through unchanged.
  void anychat_client_set_connection_callback(
    AnyChatClientHandle handle,
    ffi.Pointer<ffi.Void> userdata,
    ffi.Pointer<
            ffi.NativeFunction<
                ffi.Void Function(
                    ffi.Pointer<ffi.Void> userdata, ffi.Int state)>>
        callback,
  ) {
    return _anychat_client_set_connection_callback(
      handle,
      userdata,
      callback,
    );
  }

  late final _anychat_client_set_connection_callbackPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  AnyChatClientHandle,
                  ffi.Pointer<ffi.Void>,
                  ffi.Pointer<
                      ffi.NativeFunction<
                          ffi.Void Function(ffi.Pointer<ffi.Void> userdata,
                              ffi.Int state)>>)>>(
      'anychat_client_set_connection_callback');
  late final _anychat_client_set_connection_callback =
      _anychat_client_set_connection_callbackPtr.asFunction<
          void Function(
              AnyChatClientHandle,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<
                  ffi.NativeFunction<
                      ffi.Void Function(
                          ffi.Pointer<ffi.Void> userdata, ffi.Int state)>>)>();

  /// ---- Sub-module accessors ----
  /// The returned handles are owned by the client; do NOT destroy them separately.
  AnyChatAuthHandle anychat_client_get_auth(
    AnyChatClientHandle handle,
  ) {
    return _anychat_client_get_auth(
      handle,
    );
  }

  late final _anychat_client_get_authPtr = _lookup<
          ffi.NativeFunction<AnyChatAuthHandle Function(AnyChatClientHandle)>>(
      'anychat_client_get_auth');
  late final _anychat_client_get_auth = _anychat_client_get_authPtr
      .asFunction<AnyChatAuthHandle Function(AnyChatClientHandle)>();

  AnyChatMessageHandle anychat_client_get_message(
    AnyChatClientHandle handle,
  ) {
    return _anychat_client_get_message(
      handle,
    );
  }

  late final _anychat_client_get_messagePtr = _lookup<
          ffi
          .NativeFunction<AnyChatMessageHandle Function(AnyChatClientHandle)>>(
      'anychat_client_get_message');
  late final _anychat_client_get_message = _anychat_client_get_messagePtr
      .asFunction<AnyChatMessageHandle Function(AnyChatClientHandle)>();

  AnyChatConvHandle anychat_client_get_conversation(
    AnyChatClientHandle handle,
  ) {
    return _anychat_client_get_conversation(
      handle,
    );
  }

  late final _anychat_client_get_conversationPtr = _lookup<
          ffi.NativeFunction<AnyChatConvHandle Function(AnyChatClientHandle)>>(
      'anychat_client_get_conversation');
  late final _anychat_client_get_conversation =
      _anychat_client_get_conversationPtr
          .asFunction<AnyChatConvHandle Function(AnyChatClientHandle)>();

  AnyChatFriendHandle anychat_client_get_friend(
    AnyChatClientHandle handle,
  ) {
    return _anychat_client_get_friend(
      handle,
    );
  }

  late final _anychat_client_get_friendPtr = _lookup<
          ffi
          .NativeFunction<AnyChatFriendHandle Function(AnyChatClientHandle)>>(
      'anychat_client_get_friend');
  late final _anychat_client_get_friend = _anychat_client_get_friendPtr
      .asFunction<AnyChatFriendHandle Function(AnyChatClientHandle)>();

  AnyChatGroupHandle anychat_client_get_group(
    AnyChatClientHandle handle,
  ) {
    return _anychat_client_get_group(
      handle,
    );
  }

  late final _anychat_client_get_groupPtr = _lookup<
          ffi.NativeFunction<AnyChatGroupHandle Function(AnyChatClientHandle)>>(
      'anychat_client_get_group');
  late final _anychat_client_get_group = _anychat_client_get_groupPtr
      .asFunction<AnyChatGroupHandle Function(AnyChatClientHandle)>();

  AnyChatFileHandle anychat_client_get_file(
    AnyChatClientHandle handle,
  ) {
    return _anychat_client_get_file(
      handle,
    );
  }

  late final _anychat_client_get_filePtr = _lookup<
          ffi.NativeFunction<AnyChatFileHandle Function(AnyChatClientHandle)>>(
      'anychat_client_get_file');
  late final _anychat_client_get_file = _anychat_client_get_filePtr
      .asFunction<AnyChatFileHandle Function(AnyChatClientHandle)>();

  AnyChatUserHandle anychat_client_get_user(
    AnyChatClientHandle handle,
  ) {
    return _anychat_client_get_user(
      handle,
    );
  }

  late final _anychat_client_get_userPtr = _lookup<
          ffi.NativeFunction<AnyChatUserHandle Function(AnyChatClientHandle)>>(
      'anychat_client_get_user');
  late final _anychat_client_get_user = _anychat_client_get_userPtr
      .asFunction<AnyChatUserHandle Function(AnyChatClientHandle)>();

  AnyChatCallHandle anychat_client_get_call(
    AnyChatClientHandle handle,
  ) {
    return _anychat_client_get_call(
      handle,
    );
  }

  late final _anychat_client_get_callPtr = _lookup<
          ffi.NativeFunction<AnyChatCallHandle Function(AnyChatClientHandle)>>(
      'anychat_client_get_call');
  late final _anychat_client_get_call = _anychat_client_get_callPtr
      .asFunction<AnyChatCallHandle Function(AnyChatClientHandle)>();

  /// Return cached + DB list (pinned first, then by last_msg_time desc).
  int anychat_conv_get_list(
    AnyChatConvHandle handle,
    ffi.Pointer<AnyChatConvListCallback_C> callback,
  ) {
    return _anychat_conv_get_list(
      handle,
      callback,
    );
  }

  late final _anychat_conv_get_listPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  AnyChatConvHandle, ffi.Pointer<AnyChatConvListCallback_C>)>>(
      'anychat_conv_get_list');
  late final _anychat_conv_get_list = _anychat_conv_get_listPtr.asFunction<
      int Function(
          AnyChatConvHandle, ffi.Pointer<AnyChatConvListCallback_C>)>();

  /// ---- Friend operations ----
  int anychat_friend_get_list(
    AnyChatFriendHandle handle,
    ffi.Pointer<AnyChatFriendListCallback_C> callback,
  ) {
    return _anychat_friend_get_list(
      handle,
      callback,
    );
  }

  late final _anychat_friend_get_listPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(AnyChatFriendHandle,
                  ffi.Pointer<AnyChatFriendListCallback_C>)>>(
      'anychat_friend_get_list');
  late final _anychat_friend_get_list = _anychat_friend_get_listPtr.asFunction<
      int Function(
          AnyChatFriendHandle, ffi.Pointer<AnyChatFriendListCallback_C>)>();

  /// Send a plain-text message to a conversation.
  /// Returns ANYCHAT_OK if the request was dispatched.
  int anychat_message_send_text(
    AnyChatMessageHandle handle,
    ffi.Pointer<ffi.Char> conv_id,
    ffi.Pointer<ffi.Char> content,
    ffi.Pointer<AnyChatMessageCallback_C> callback,
  ) {
    return _anychat_message_send_text(
      handle,
      conv_id,
      content,
      callback,
    );
  }

  late final _anychat_message_send_textPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  AnyChatMessageHandle,
                  ffi.Pointer<ffi.Char>,
                  ffi.Pointer<ffi.Char>,
                  ffi.Pointer<AnyChatMessageCallback_C>)>>(
      'anychat_message_send_text');
  late final _anychat_message_send_text =
      _anychat_message_send_textPtr.asFunction<
          int Function(AnyChatMessageHandle, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, ffi.Pointer<AnyChatMessageCallback_C>)>();

  /// Fetch message history before a given timestamp.
  /// before_timestamp_ms: 0 means "fetch the most recent messages".
  /// limit: maximum number of messages to return.
  int anychat_message_get_history(
    AnyChatMessageHandle handle,
    ffi.Pointer<ffi.Char> conv_id,
    int before_timestamp_ms,
    int limit,
    ffi.Pointer<AnyChatMessageListCallback_C> callback,
  ) {
    return _anychat_message_get_history(
      handle,
      conv_id,
      before_timestamp_ms,
      limit,
      callback,
    );
  }

  late final _anychat_message_get_historyPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  AnyChatMessageHandle,
                  ffi.Pointer<ffi.Char>,
                  ffi.Int64,
                  ffi.Int,
                  ffi.Pointer<AnyChatMessageListCallback_C>)>>(
      'anychat_message_get_history');
  late final _anychat_message_get_history =
      _anychat_message_get_historyPtr.asFunction<
          int Function(AnyChatMessageHandle, ffi.Pointer<ffi.Char>, int, int,
              ffi.Pointer<AnyChatMessageListCallback_C>)>();
}

final class AnyChatClient_T extends ffi.Opaque {}

/// ---- Opaque handle types ----
typedef AnyChatClientHandle = ffi.Pointer<AnyChatClient_T>;

final class AnyChatAuthManager_T extends ffi.Opaque {}

typedef AnyChatAuthHandle = ffi.Pointer<AnyChatAuthManager_T>;

final class AnyChatMessage_T extends ffi.Opaque {}

typedef AnyChatMessageHandle = ffi.Pointer<AnyChatMessage_T>;

final class AnyChatConversation_T extends ffi.Opaque {}

typedef AnyChatConvHandle = ffi.Pointer<AnyChatConversation_T>;

final class AnyChatFriend_T extends ffi.Opaque {}

typedef AnyChatFriendHandle = ffi.Pointer<AnyChatFriend_T>;

final class AnyChatGroup_T extends ffi.Opaque {}

typedef AnyChatGroupHandle = ffi.Pointer<AnyChatGroup_T>;

final class AnyChatFile_T extends ffi.Opaque {}

typedef AnyChatFileHandle = ffi.Pointer<AnyChatFile_T>;

final class AnyChatUser_T extends ffi.Opaque {}

typedef AnyChatUserHandle = ffi.Pointer<AnyChatUser_T>;

final class AnyChatCall_T extends ffi.Opaque {}

typedef AnyChatCallHandle = ffi.Pointer<AnyChatCall_T>;

/// ---- Plain-old-data structs ----
final class AnyChatAuthToken_C extends ffi.Struct {
  @ffi.Array.multi([512])
  external ffi.Array<ffi.Char> access_token;

  @ffi.Array.multi([512])
  external ffi.Array<ffi.Char> refresh_token;

  @ffi.Int64()
  external int expires_at_ms;
}

final class AnyChatUserInfo_C extends ffi.Struct {
  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> user_id;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> username;

  @ffi.Array.multi([512])
  external ffi.Array<ffi.Char> avatar_url;

  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> signature;

  /// 0=unknown, 1=male, 2=female
  @ffi.Int32()
  external int gender;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> region;

  @ffi.Int()
  external int is_friend;

  @ffi.Int()
  external int is_blocked;
}

final class AnyChatMessage_C extends ffi.Struct {
  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> message_id;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> local_id;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> conv_id;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> sender_id;

  @ffi.Int32()
  external int content_type;

  /// ANYCHAT_MSG_*
  @ffi.Int()
  external int type;

  /// heap-allocated; free via anychat_free_message()
  external ffi.Pointer<ffi.Char> content;

  @ffi.Int64()
  external int seq;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> reply_to;

  @ffi.Int64()
  external int timestamp_ms;

  /// 0=normal, 1=recalled, 2=deleted
  @ffi.Int()
  external int status;

  /// ANYCHAT_SEND_*
  @ffi.Int()
  external int send_state;

  @ffi.Int()
  external int is_read;
}

final class AnyChatMessageList_C extends ffi.Struct {
  external ffi.Pointer<AnyChatMessage_C> items;

  @ffi.Int()
  external int count;
}

final class AnyChatConversation_C extends ffi.Struct {
  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> conv_id;

  /// ANYCHAT_CONV_*
  @ffi.Int()
  external int conv_type;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> target_id;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> last_msg_id;

  @ffi.Array.multi([512])
  external ffi.Array<ffi.Char> last_msg_text;

  @ffi.Int64()
  external int last_msg_time_ms;

  @ffi.Int32()
  external int unread_count;

  @ffi.Int()
  external int is_pinned;

  @ffi.Int()
  external int is_muted;

  /// seconds, 0 = disabled
  @ffi.Int32()
  external int burn_after_reading;

  /// seconds, 0 = disabled
  @ffi.Int32()
  external int auto_delete_duration;

  @ffi.Int64()
  external int updated_at_ms;
}

final class AnyChatConversationList_C extends ffi.Struct {
  external ffi.Pointer<AnyChatConversation_C> items;

  @ffi.Int()
  external int count;
}

final class AnyChatFriend_C extends ffi.Struct {
  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> user_id;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> remark;

  @ffi.Int64()
  external int updated_at_ms;

  @ffi.Int()
  external int is_deleted;

  external AnyChatUserInfo_C user_info;
}

final class AnyChatFriendList_C extends ffi.Struct {
  external ffi.Pointer<AnyChatFriend_C> items;

  @ffi.Int()
  external int count;
}

final class AnyChatAuthTokenCallback_C extends ffi.Struct {
  external ffi.Pointer<ffi.Void> userdata;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void> userdata,
              ffi.Pointer<AnyChatAuthToken_C> token)>> on_success;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void> userdata, ffi.Int code,
              ffi.Pointer<ffi.Char> error)>> on_error;
}

final class AnyChatAuthResultCallback_C extends ffi.Struct {
  external ffi.Pointer<ffi.Void> userdata;

  external ffi.Pointer<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> userdata)>>
      on_success;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void> userdata, ffi.Int code,
              ffi.Pointer<ffi.Char> error)>> on_error;
}

/// ---- Client configuration ----
final class AnyChatClientConfig_C extends ffi.Struct {
  /// WebSocket gateway, e.g. "wss://api.anychat.io"
  external ffi.Pointer<ffi.Char> gateway_url;

  /// HTTP API base, e.g. "https://api.anychat.io/api/v1"
  external ffi.Pointer<ffi.Char> api_base_url;

  /// Unique device identifier
  external ffi.Pointer<ffi.Char> device_id;

  /// SQLite database file path
  external ffi.Pointer<ffi.Char> db_path;

  /// default: 10000
  @ffi.Int()
  external int connect_timeout_ms;

  /// default: 5
  @ffi.Int()
  external int max_reconnect_attempts;

  /// 1 = enabled (default), 0 = disabled
  @ffi.Int()
  external int auto_reconnect;
}

final class AnyChatConvListCallback_C extends ffi.Struct {
  external ffi.Pointer<ffi.Void> userdata;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void> userdata,
              ffi.Pointer<AnyChatConversationList_C> list)>> on_success;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void> userdata, ffi.Int code,
              ffi.Pointer<ffi.Char> error)>> on_error;
}

final class AnyChatFriendListCallback_C extends ffi.Struct {
  external ffi.Pointer<ffi.Void> userdata;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void> userdata,
              ffi.Pointer<AnyChatFriendList_C> list)>> on_success;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void> userdata, ffi.Int code,
              ffi.Pointer<ffi.Char> error)>> on_error;
}

final class AnyChatMessageCallback_C extends ffi.Struct {
  external ffi.Pointer<ffi.Void> userdata;

  external ffi.Pointer<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> userdata)>>
      on_success;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void> userdata, ffi.Int code,
              ffi.Pointer<ffi.Char> error)>> on_error;
}

final class AnyChatMessageListCallback_C extends ffi.Struct {
  external ffi.Pointer<ffi.Void> userdata;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void> userdata,
              ffi.Pointer<AnyChatMessageList_C> list)>> on_success;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void> userdata, ffi.Int code,
              ffi.Pointer<ffi.Char> error)>> on_error;
}

const int ANYCHAT_OK = 0;

const int ANYCHAT_ERROR_INVALID_PARAM = 1;

const int ANYCHAT_ERROR_AUTH = 2;

const int ANYCHAT_ERROR_NETWORK = 3;

const int ANYCHAT_ERROR_TIMEOUT = 4;

const int ANYCHAT_ERROR_NOT_FOUND = 5;

const int ANYCHAT_ERROR_ALREADY_EXISTS = 6;

const int ANYCHAT_ERROR_INTERNAL = 7;

const int ANYCHAT_ERROR_NOT_LOGGED_IN = 8;

const int ANYCHAT_ERROR_TOKEN_EXPIRED = 9;

const int ANYCHAT_STATE_DISCONNECTED = 0;

const int ANYCHAT_STATE_CONNECTING = 1;

const int ANYCHAT_STATE_CONNECTED = 2;

const int ANYCHAT_STATE_RECONNECTING = 3;

const int ANYCHAT_MSG_TEXT = 0;

const int ANYCHAT_MSG_IMAGE = 1;

const int ANYCHAT_MSG_FILE = 2;

const int ANYCHAT_MSG_AUDIO = 3;

const int ANYCHAT_MSG_VIDEO = 4;

const int ANYCHAT_MESSAGE_CONTENT_TYPE_UNSPECIFIED = 0;

const int ANYCHAT_MESSAGE_CONTENT_TYPE_TEXT = 1;

const int ANYCHAT_MESSAGE_CONTENT_TYPE_IMAGE = 2;

const int ANYCHAT_MESSAGE_CONTENT_TYPE_VIDEO = 3;

const int ANYCHAT_MESSAGE_CONTENT_TYPE_AUDIO = 4;

const int ANYCHAT_MESSAGE_CONTENT_TYPE_FILE = 5;

const int ANYCHAT_MESSAGE_CONTENT_TYPE_LOCATION = 6;

const int ANYCHAT_MESSAGE_CONTENT_TYPE_CARD = 7;

const int ANYCHAT_CONV_PRIVATE = 0;

const int ANYCHAT_CONV_GROUP = 1;

const int ANYCHAT_SEND_PENDING = 0;

const int ANYCHAT_SEND_SENT = 1;

const int ANYCHAT_SEND_FAILED = 2;

const int ANYCHAT_CALL_AUDIO = 0;

const int ANYCHAT_CALL_VIDEO = 1;

const int ANYCHAT_CALL_STATUS_RINGING = 0;

const int ANYCHAT_CALL_STATUS_CONNECTED = 1;

const int ANYCHAT_CALL_STATUS_ENDED = 2;

const int ANYCHAT_CALL_STATUS_REJECTED = 3;

const int ANYCHAT_CALL_STATUS_MISSED = 4;

const int ANYCHAT_CALL_STATUS_CANCELLED = 5;

const int ANYCHAT_GROUP_ROLE_OWNER = 1;

const int ANYCHAT_GROUP_ROLE_ADMIN = 2;

const int ANYCHAT_GROUP_ROLE_MEMBER = 3;
